### ISSUE TITLE
does this work with the simple .delay. syntax?

### ISSUE THREAD

**Issue by stuffmc** [markbates/dj_remixes#9]
I'm not using `Delayed::Job.enqueue` but rather simply `object.delay.method` which works fine in my case. I don't see AirBrake being called in this case. Not a big deal if I have to change my code to `Delayed::Job.enqueue` but just wanted to know if this is a Bug or not.

**Comment by markbates** [comment]
Unfortunately it doesn't work like that. All jobs must inherit from DJ::Worker in order to get all the funky cool goodness. :)

**Comment by stuffmc** [comment]
As I mentioned, not a huge deal ;-) I guess it's a good way to have be obliged of doing it _the right way_ :-) Thanks for your help.
